= Scripts QML pour positions

(by Sitting Bugle . Please provide feedback to gru.framework@free.fr . Language is French because features are specific to French "beaux arts" brassbands)

Ces scripts sont des transformations des scripts de position écrits par Tony Babecka et autres (qu'ils soient remerciés!).

Sauf qu'ici les positions des instruments à pistons sont représentés par des sigles au lieu de numéros  (par ex: "iĪi" au lieu de 13 )
Bien entendu on peut se référer aux scripts d'origine si on souhaite conserver le standard avec des chiffres.

Les prolongations de notes sont marquées "–". Les accords (ça arrive) donnent des doigtés en colonne.

Pour les trombones les positions de la coulisse suivent un code différent: 

 - en haut (position "fanfare"): c'est le décalage par demi-tons à partir de la position marquée 0 (au lieu de 1 en position standard)

 - en bas (position "classique") :  le numéro de position standard.

Il faudrait que l'on puisse déclencher les scripts sur un instrument particulier sur une fenêtre générale (par sélection).
Pour le moment on ne peut le faire que sur une fenêtre dédiée à la partie de l'instrument.

Manque un script pour les pichottes en MIb (à écrire).

== pistonsTrompette

Script pour trompette, cornet, bugle . Les sigles indiquent aussi l'usage des gachettes ("trigger") par ex: "≾iiĪ" indique l'usage de 
la première extension, "iĪi≿" de la deuxième extension (position moyenne) et "iii≽" de la deuxième extension (à fond).

== pistonsBasse

Script pour saxhorn baryton, basse et euphoniums (pour l'instant pas d'indication sur l'usage du 4° piston... mais ça viendra)

== pistonsSouba

Script pour les contre-basses (souba, hélicon, tubas divers)

== positionsTrombone

Script pour afficher les positions trombone en combinant les positions "classiques" et "fanfare"

== positionsTromboneClassique

Script pour afficher les positions trombone "classiques" 

== positionsTromboneFanfare

Script pour afficher les positions trombone "Fanfare" 
(il y a aussi un petit sigle pour de légers décalages supplémentaires par rapport aux positions qui restent toujours approximatives puisque
calquées sur celles des instruments tempérés - exemple "1½≿" )

== Bugs connus

Ne gère pas les voix multiples... à faire!



